name: graphein-dev
channels:
- conda-forge
- plotly
- pytorch
dependencies:
- python=3.8
- biopython
- biopandas
- black
- conda
- flake8
- interrogate
- ipympl
- isort
- jupyter
- jupyterlab
- mamba
- matplotlib
- mypy
- nbstripout
- networkx
- nodejs
- numpy
- pandas
- pip
- plotly
- pre-commit
- pycodestyle
- pydantic
- pydocstyle
- pytest
- pytest-cov
- pytest-xdist
- pytorch=1.7.1
- rdkit
- scikit-learn
- scipy
- sphinx
- tqdm
- xarray
- pip:
  - bioservices
  - biovec
  - click
  - multipledispatch
  - nbval
  - pytorch3d
  - propy
  - pyyaml
  - sphinx_rtd_theme
  - versioneer
  - wget
