name: graphein-dev
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8
- biopython
- black
- conda
- flake8
- isort
- mamba
- matplotlib
- mypy
- nbstripout
- networkx
- numpy
- pandas
- pip
- pre-commit
- pycodestyle
- pydocstyle
- pytest
- pytest-cov
- pytest-xdist
- rdkit
- scipy
- scikit-learn
- pytorch=1.7.1
- xarray
- ipympl
- pydantic
- interrogate
- pip:
    - bioservices
    - propy
    - pytorch3d
    - biovec
    - multipledispatch
    - wget
    - git+https://www.github.com/a-r-j/graphein@protein_vis
