name: graphein-dev
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8
- biopython
- biopandas
- black
- conda
- flake8
- isort
- ipympl
- mamba
- matplotlib
- mypy
- nbstripout
- networkx
- numpy
- pandas
- pip
- pre-commit
- pycodestyle
- pydocstyle
- pytest
- pytest-cov
- pytest-xdist
- pytorch=1.7.1
- rdkit
- scipy
- scikit-learn
- xarray
- jupyter
- jupyterlab
- pydantic
- interrogate
- pip:
  - bioservices
  - versioneer
  - pytorch3d
  - propy
  - biovec
  - multipledispatch
  - pytorch3d
  - wget
