name: graphein-dev-test
channels:
- pytorch
- pytorch3d
- dglteam
- conda-forge
- anaconda
- bioconda
- fvcore
- iopath
- nvidia
- plotly
- rusty1s
- schrodinger
dependencies:
- python=3.8
- biopython
- biopandas
- black
- conda
- cudatoolkit=11.1
- dgl
- flake8
- furo
- fvcore
- interrogate
- iopath
- ipympl
- isort
- jupyter
- jupyterlab
- mamba
- matplotlib
- anaconda::multipledispatch
- mypy
- nbsphinx
- nbsphinx-link
- sphinx_rtd_theme
- nbstripout
- nbval
- networkx
- nodejs
- numpy
- pandas
- pip
- plotly
- pre-commit
- pycodestyle
- pydantic
- pydocstyle
- pymol
- pytest
- pytest-cov
- pytest-xdist
- pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
- pytorch3d
- pytorch-geometric
- pytorch-lightning
- pyyaml
- rdkit
- scikit-learn
- scipy
- sphinx
- tqdm
- torchvision
- wget
- xarray
- pip:
  - biovec
  - click
  - propy3
  - versioneer
  - git+https://github.com/a-r-j/graphein

