# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests on examples

on:
  [pull_request]

jobs:
  build:
    runs-on: "ubuntu-18.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - name: Setup anaconda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      - name: Build environment
        # if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          conda env create -f environment-dev.yml

      - name: Install Graphein
        run: |
          source activate graphein-dev
          pip install -e .

      - name: Run tests
        run: |
          source activate graphein-dev
          pytest --nbval-lax --current-env

      - name: Run example notebooks
        run: |
          grep -l smoke_test notebooks/*.ipynb | pytest --nbval-lax --current-env
